[package]
name = "stylus-common"
authors = ["Fig"]
edition.workspace = true
license.workspace = true
version = "0.1.0"

[lib]
crate-type = ["lib"]

[dependencies]
stylus-sdk.workspace = true
alloy-sol-types.workspace = true