[package]
name = "stylus-common"
authors = ["Fig"]
edition = "2021"
license = "MIT"
version = "0.0.1"

[lib]
crate-type = ["lib"]

[dependencies]
stylus-sdk.workspace = true
alloy-sol-types.workspace = true


