[package]
name = "stylus-imt"
authors = ["Fig"]
edition.workspace = true
license.workspace = true
version = "0.0.1"

[dependencies]
alloy-primitives.workspace = true
stylus-sdk.workspace = true
alloy-sol-types.workspace = true
stylus-common = { path = "../common" }
openzeppelin-poseidon = { path = "../poseidon", default-features = false }

[dev-dependencies]
tokio.workspace = true
eyre.workspace = true

[features]
export-abi = ["stylus-sdk/export-abi"]

[[bin]]
name = "stylus-imt"
path = "src/main.rs"

[lib]
crate-type = ["lib","cdylib"]
