[package]
name = "stylus-imt"
authors = ["Fig"]
edition.workspace = true
license.workspace = true
version = "0.0.1"

[dependencies]
alloy-primitives.workspace = true
stylus-sdk.workspace = true
alloy-sol-types.workspace = true

stylus-common = { path = "../common" }
openzeppelin-poseidon = { path = "../poseidon" }

[dev-dependencies]
alloy.workspace = true
tokio.workspace = true
eyre.workspace = true

[features]
default = ["mini-alloc"]
export-abi = ["stylus-sdk/export-abi"]
debug = ["stylus-sdk/debug"]
mini-alloc = ["stylus-sdk/mini-alloc"]

[[bin]]
name = "stylus-imt"
path = "src/main.rs"

[lib]
crate-type = ["lib","cdylib"]
