[workspace]
members = ["mixer", "imt", "poseidon2", "common"]
resolver = "2"

[workspace.dependencies]
alloy-primitives = "=0.8.20"
alloy-sol-types = "=0.8.20"
stylus-sdk = "0.9.0"
parity-scale-codec = "=3.7.5"



